<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 10 Bayes Factor | Evaluating Informative Hypotheses with Equality and Inequality Constraints: A Tutorial Using the Bayes Factor via the Encompassing Prior Approach</title>
  <meta name="description" content="This the Supplemental Material of the article “Evaluating informative hypotheses with equality and inequality constraint: A tutorial using the Bayes factor via the encompassing prior approach”" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 10 Bayes Factor | Evaluating Informative Hypotheses with Equality and Inequality Constraints: A Tutorial Using the Bayes Factor via the Encompassing Prior Approach" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://ClaudioZandonella.github.io/Attachment/" />
  <meta property="og:image" content="https://ClaudioZandonella.github.io/Attachment//images/logo_psicostat.png" />
  <meta property="og:description" content="This the Supplemental Material of the article “Evaluating informative hypotheses with equality and inequality constraint: A tutorial using the Bayes factor via the encompassing prior approach”" />
  <meta name="github-repo" content="ClaudioZandonella/Attachment" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 10 Bayes Factor | Evaluating Informative Hypotheses with Equality and Inequality Constraints: A Tutorial Using the Bayes Factor via the Encompassing Prior Approach" />
  
  <meta name="twitter:description" content="This the Supplemental Material of the article “Evaluating informative hypotheses with equality and inequality constraint: A tutorial using the Bayes factor via the encompassing prior approach”" />
  <meta name="twitter:image" content="https://ClaudioZandonella.github.io/Attachment//images/logo_psicostat.png" />

<meta name="author" content="Claudio Zandonella Callegher, Tatiana Marci, Pietro De Carli, and Gianmarco Altoè" />


<meta name="date" content="2021-11-28" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="model-comparison-int.html"/>
<link rel="next" href="conclusion-int.html"/>
<script src="libs/header-attrs-2.9/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="assets/style.css" type="text/css" />
<link rel="stylesheet" href="assets/toc.css" type="text/css" />
<link rel="stylesheet" href="assets/custom.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="toc-logo"><a href="./"><img src="images/hex_psicostat.png"></a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#study-summary"><i class="fa fa-check"></i>Study Summary</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#supplemental-material-structure"><i class="fa fa-check"></i>Supplemental Material Structure</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#github"><i class="fa fa-check"></i>GitHub</a></li>
</ul></li>
<li class="part"><span><b>Presentation</b></span></li>
<li class="chapter" data-level="1" data-path="case-study.html"><a href="case-study.html"><i class="fa fa-check"></i><b>1</b> Case Study</a>
<ul>
<li class="chapter" data-level="1.1" data-path="case-study.html"><a href="case-study.html#aim-of-the-study"><i class="fa fa-check"></i><b>1.1</b> Aim of the Study</a></li>
<li class="chapter" data-level="1.2" data-path="case-study.html"><a href="case-study.html#the-study-sample"><i class="fa fa-check"></i><b>1.2</b> The Study Sample</a></li>
<li class="chapter" data-level="1.3" data-path="case-study.html"><a href="case-study.html#attachment-styles"><i class="fa fa-check"></i><b>1.3</b> Attachment Styles</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="case-study.html"><a href="case-study.html#mother-cluster-analysis"><i class="fa fa-check"></i><b>1.3.1</b> Mother Cluster Analysis</a></li>
<li class="chapter" data-level="1.3.2" data-path="case-study.html"><a href="case-study.html#father-cluster-analysis"><i class="fa fa-check"></i><b>1.3.2</b> Father Cluster Analysis</a></li>
<li class="chapter" data-level="1.3.3" data-path="case-study.html"><a href="case-study.html#mother-and-father"><i class="fa fa-check"></i><b>1.3.3</b> Mother and Father</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="case-study.html"><a href="case-study.html#children-outcomes"><i class="fa fa-check"></i><b>1.4</b> Children Outcomes</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="case-study.html"><a href="case-study.html#externalizing-problems-1"><i class="fa fa-check"></i><b>1.4.1</b> Externalizing Problems</a></li>
<li class="chapter" data-level="1.4.2" data-path="case-study.html"><a href="case-study.html#internalizing-problems-1"><i class="fa fa-check"></i><b>1.4.2</b> Internalizing Problems</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>Externalizing Problems</b></span></li>
<li class="chapter" data-level="2" data-path="model-choice-ext.html"><a href="model-choice-ext.html"><i class="fa fa-check"></i><b>2</b> Models Family Choice</a>
<ul>
<li class="chapter" data-level="2.1" data-path="model-choice-ext.html"><a href="model-choice-ext.html#negative-binomial"><i class="fa fa-check"></i><b>2.1</b> Negative Binomial</a></li>
<li class="chapter" data-level="2.2" data-path="model-choice-ext.html"><a href="model-choice-ext.html#zero-inflated-negative-binomial"><i class="fa fa-check"></i><b>2.2</b> Zero Inflated Negative Binomial</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="nhst-ext.html"><a href="nhst-ext.html"><i class="fa fa-check"></i><b>3</b> NHST</a></li>
<li class="chapter" data-level="4" data-path="model-comparison-ext.html"><a href="model-comparison-ext.html"><i class="fa fa-check"></i><b>4</b> Model Comparison</a>
<ul>
<li class="chapter" data-level="4.1" data-path="model-comparison-ext.html"><a href="model-comparison-ext.html#formalize-models"><i class="fa fa-check"></i><b>4.1</b> Formalize Models</a></li>
<li class="chapter" data-level="4.2" data-path="model-comparison-ext.html"><a href="model-comparison-ext.html#aic-and-bic-results"><i class="fa fa-check"></i><b>4.2</b> AIC and BIC Results</a></li>
<li class="chapter" data-level="4.3" data-path="model-comparison-ext.html"><a href="model-comparison-ext.html#selected-model"><i class="fa fa-check"></i><b>4.3</b> Selected Model</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="BF-ext.html"><a href="BF-ext.html"><i class="fa fa-check"></i><b>5</b> Bayes Factor</a>
<ul>
<li class="chapter" data-level="5.1" data-path="BF-ext.html"><a href="BF-ext.html#encompassing-model"><i class="fa fa-check"></i><b>5.1</b> Encompassing Model</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="BF-ext.html"><a href="BF-ext.html#prior-choice"><i class="fa fa-check"></i><b>5.1.1</b> Prior Choice</a></li>
<li class="chapter" data-level="5.1.2" data-path="BF-ext.html"><a href="BF-ext.html#posterior"><i class="fa fa-check"></i><b>5.1.2</b> Posterior</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="BF-ext.html"><a href="BF-ext.html#hypothesis-matrices"><i class="fa fa-check"></i><b>5.2</b> Hypothesis Matrices</a></li>
<li class="chapter" data-level="5.3" data-path="BF-ext.html"><a href="BF-ext.html#centering-and-adjusting"><i class="fa fa-check"></i><b>5.3</b> Centering and Adjusting</a></li>
<li class="chapter" data-level="5.4" data-path="BF-ext.html"><a href="BF-ext.html#results-and-sensitivity"><i class="fa fa-check"></i><b>5.4</b> Results and Sensitivity</a></li>
<li class="chapter" data-level="5.5" data-path="BF-ext.html"><a href="BF-ext.html#selected-model-1"><i class="fa fa-check"></i><b>5.5</b> Selected Model</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="conclusion-ext.html"><a href="conclusion-ext.html"><i class="fa fa-check"></i><b>6</b> Conclusions</a></li>
<li class="part"><span><b>Internalizing Problems</b></span></li>
<li class="chapter" data-level="7" data-path="model-choice-int.html"><a href="model-choice-int.html"><i class="fa fa-check"></i><b>7</b> Models Family Choice</a>
<ul>
<li class="chapter" data-level="7.1" data-path="model-choice-int.html"><a href="model-choice-int.html#zero-inflated-negative-binomial-1"><i class="fa fa-check"></i><b>7.1</b> Zero Inflated Negative Binomial</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="nhst-int.html"><a href="nhst-int.html"><i class="fa fa-check"></i><b>8</b> NHST</a></li>
<li class="chapter" data-level="9" data-path="model-comparison-int.html"><a href="model-comparison-int.html"><i class="fa fa-check"></i><b>9</b> Model Comparison</a>
<ul>
<li class="chapter" data-level="9.1" data-path="model-comparison-int.html"><a href="model-comparison-int.html#formalize-models-1"><i class="fa fa-check"></i><b>9.1</b> Formalize Models</a></li>
<li class="chapter" data-level="9.2" data-path="model-comparison-int.html"><a href="model-comparison-int.html#aic-and-bic-results-1"><i class="fa fa-check"></i><b>9.2</b> AIC and BIC Results</a></li>
<li class="chapter" data-level="9.3" data-path="model-comparison-int.html"><a href="model-comparison-int.html#selected-model-2"><i class="fa fa-check"></i><b>9.3</b> Selected Model</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="BF-int.html"><a href="BF-int.html"><i class="fa fa-check"></i><b>10</b> Bayes Factor</a>
<ul>
<li class="chapter" data-level="10.1" data-path="BF-int.html"><a href="BF-int.html#encompassing-model-1"><i class="fa fa-check"></i><b>10.1</b> Encompassing Model</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="BF-int.html"><a href="BF-int.html#prior-choice-1"><i class="fa fa-check"></i><b>10.1.1</b> Prior Choice</a></li>
<li class="chapter" data-level="10.1.2" data-path="BF-int.html"><a href="BF-int.html#posterior-1"><i class="fa fa-check"></i><b>10.1.2</b> Posterior</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="BF-int.html"><a href="BF-int.html#hypothesis-matrices-1"><i class="fa fa-check"></i><b>10.2</b> Hypothesis Matrices</a></li>
<li class="chapter" data-level="10.3" data-path="BF-int.html"><a href="BF-int.html#centering-and-adjusting-1"><i class="fa fa-check"></i><b>10.3</b> Centering and Adjusting</a></li>
<li class="chapter" data-level="10.4" data-path="BF-int.html"><a href="BF-int.html#results-and-sensitivity-1"><i class="fa fa-check"></i><b>10.4</b> Results and Sensitivity</a></li>
<li class="chapter" data-level="10.5" data-path="BF-int.html"><a href="BF-int.html#selected-model-3"><i class="fa fa-check"></i><b>10.5</b> Selected Model</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="conclusion-int.html"><a href="conclusion-int.html"><i class="fa fa-check"></i><b>11</b> Conclusions</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Evaluating Informative Hypotheses with Equality and Inequality Constraints: A Tutorial Using the Bayes Factor via the Encompassing Prior Approach</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<head>
  <meta name="viewport" content="width=device-width,minimum-scale=1.0,maximum-scale=10.0,initial-scale=1.0">
  <!--script src="https://kit.fontawesome.com/6a26f47516.js"></script-->
  <script src="assets/hideOutput.js"></script>
  <link href="assets/style.css" rel="stylesheet">
</head>



<div class="hero-image-container">
  <img class= "hero-image" src="images/banner.png">
</div>
<div id="BF-int" class="section level1" number="10">
<h1><span class="header-section-number">Chapter 10</span> Bayes Factor</h1>
<div id="encompassing-model-1" class="section level2" number="10.1">
<h2><span class="header-section-number">10.1</span> Encompassing Model</h2>
<p>We define a Zero-Inflated Negative Binomial (ZINB) mixed-effects considering only the role of gender as a fixed effect and children’s classroom ID as a random effect for <span class="math inline">\(p\)</span>. Whereas, regarding <span class="math inline">\(\mu\)</span>, we consider the interaction between mother and father attachment together with gender as fixed effects and children’s classroom ID as a random effect. In the R formula syntax, we have</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="BF-int.html#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># formula for p</span></span>
<span id="cb52-2"><a href="BF-int.html#cb52-2" aria-hidden="true" tabindex="-1"></a>p <span class="sc">~</span> gender <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>ID_class)</span>
<span id="cb52-3"><a href="BF-int.html#cb52-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-4"><a href="BF-int.html#cb52-4" aria-hidden="true" tabindex="-1"></a><span class="co"># formula for mu</span></span>
<span id="cb52-5"><a href="BF-int.html#cb52-5" aria-hidden="true" tabindex="-1"></a>mu <span class="sc">~</span> gender <span class="sc">+</span> mother <span class="sc">*</span> father <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>ID_class)</span></code></pre></div>
<div id="prior-choice-1" class="section level3" number="10.1.1">
<h3><span class="header-section-number">10.1.1</span> Prior Choice</h3>
<p>We set the same prior as for the externalizing problems analysis. The resulting prior settings are</p>
<pre><code>##                   prior     class                          coef    group resp dpar nlpar bound       source
##            normal(0, 3)         b                                                                      user
##            normal(0, 3)         b                 fatherAnxious                                (vectorized)
##            normal(0, 3)         b                fatherAvoidant                                (vectorized)
##            normal(0, 3)         b                 fatherFearful                                (vectorized)
##            normal(0, 3)         b                       genderM                                (vectorized)
##            normal(0, 3)         b                 motherAnxious                                (vectorized)
##            normal(0, 3)         b   motherAnxious:fatherAnxious                                (vectorized)
##            normal(0, 3)         b  motherAnxious:fatherAvoidant                                (vectorized)
##            normal(0, 3)         b   motherAnxious:fatherFearful                                (vectorized)
##            normal(0, 3)         b                motherAvoidant                                (vectorized)
##            normal(0, 3)         b  motherAvoidant:fatherAnxious                                (vectorized)
##            normal(0, 3)         b motherAvoidant:fatherAvoidant                                (vectorized)
##            normal(0, 3)         b  motherAvoidant:fatherFearful                                (vectorized)
##            normal(0, 3)         b                 motherFearful                                (vectorized)
##            normal(0, 3)         b   motherFearful:fatherAnxious                                (vectorized)
##            normal(0, 3)         b  motherFearful:fatherAvoidant                                (vectorized)
##            normal(0, 3)         b   motherFearful:fatherFearful                                (vectorized)
##            normal(0, 3)         b                                               zi             (vectorized)
##            normal(0, 3)         b                       genderM                 zi             (vectorized)
##  student_t(3, 0.7, 2.5) Intercept                                                                   default
##          logistic(0, 1) Intercept                                               zi                  default
##    student_t(3, 0, 2.5)        sd                                                                   default
##    student_t(3, 0, 2.5)        sd                                               zi                  default
##    student_t(3, 0, 2.5)        sd                               ID_class                       (vectorized)
##    student_t(3, 0, 2.5)        sd                     Intercept ID_class                       (vectorized)
##    student_t(3, 0, 2.5)        sd                               ID_class        zi             (vectorized)
##    student_t(3, 0, 2.5)        sd                     Intercept ID_class        zi             (vectorized)
##       gamma(0.01, 0.01)     shape                                                                   default</code></pre>
</div>
<div id="posterior-1" class="section level3" number="10.1.2">
<h3><span class="header-section-number">10.1.2</span> Posterior</h3>
<p>The encompassing model is estimated using 6 independent chains with 10,000 iterations (warm-up 2,000). Summary of the encompassing model is presented below.</p>
<pre><code>##  Family: zero_inflated_negbinomial 
##   Links: mu = log; shape = identity; zi = logit 
## Formula: internalizing_sum ~ gender + mother * father + (1 | ID_class) 
##          zi ~ gender + (1 | ID_class)
##    Data: data (Number of observations: 847) 
## Samples: 6 chains, each with iter = 10000; warmup = 2000; thin = 1;
##          total post-warmup samples = 48000
## 
## Group-Level Effects: 
## ~ID_class (Number of levels: 50) 
##                  Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## sd(Intercept)        0.44      0.08     0.29     0.62 1.00     9467    20478
## sd(zi_Intercept)     2.24      0.56     1.37     3.52 1.00    22914    28211
## 
## Population-Level Effects: 
##                               Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## Intercept                         0.83      0.13     0.57     1.07 1.00    21805    30756
## zi_Intercept                     -2.94      0.70    -4.58    -1.84 1.00    23476    24791
## genderM                           0.08      0.07    -0.06     0.22 1.00    69575    38126
## motherAnxious                     0.46      0.17     0.13     0.79 1.00    33349    37383
## motherAvoidant                   -0.08      0.25    -0.56     0.41 1.00    28640    33103
## motherFearful                     0.63      0.40    -0.14     1.45 1.00    28081    31710
## fatherAnxious                     0.07      0.17    -0.27     0.40 1.00    36862    37511
## fatherAvoidant                    0.08      0.18    -0.26     0.43 1.00    36867    35693
## fatherFearful                     0.36      0.34    -0.28     1.04 1.00    30611    33358
## motherAnxious:fatherAnxious      -0.24      0.24    -0.70     0.22 1.00    31718    36313
## motherAvoidant:fatherAnxious      0.24      0.31    -0.38     0.85 1.00    28308    33805
## motherFearful:fatherAnxious      -0.75      0.50    -1.75     0.22 1.00    30436    34570
## motherAnxious:fatherAvoidant     -0.23      0.24    -0.70     0.24 1.00    32215    36746
## motherAvoidant:fatherAvoidant     0.11      0.30    -0.49     0.71 1.00    27005    33164
## motherFearful:fatherAvoidant     -0.19      0.45    -1.09     0.69 1.00    27741    32785
## motherAnxious:fatherFearful      -0.47      0.40    -1.25     0.31 1.00    27639    33504
## motherAvoidant:fatherFearful      0.28      0.48    -0.67     1.21 1.00    26850    35151
## motherFearful:fatherFearful      -0.35      0.53    -1.41     0.68 1.00    24657    31248
## zi_genderM                       -0.30      0.40    -1.10     0.48 1.00    49145    34266
## 
## Family Specific Parameters: 
##       Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## shape     2.46      0.32     1.90     3.17 1.00    38857    36697
## 
## Samples were drawn using sampling(NUTS). For each parameter, Bulk_ESS
## and Tail_ESS are effective sample size measures, and Rhat is the potential
## scale reduction factor on split chains (at convergence, Rhat = 1).</code></pre>
</div>
</div>
<div id="hypothesis-matrices-1" class="section level2" number="10.2">
<h2><span class="header-section-number">10.2</span> Hypothesis Matrices</h2>
<p>Hypothesis matrices are the same as in the analysis of the externalizing problems.</p>
</div>
<div id="centering-and-adjusting-1" class="section level2" number="10.3">
<h2><span class="header-section-number">10.3</span> Centering and Adjusting</h2>
<p>Centering and adjusting procedures are the same as in the analysis of the externalizing problems.</p>
</div>
<div id="results-and-sensitivity-1" class="section level2" number="10.4">
<h2><span class="header-section-number">10.4</span> Results and Sensitivity</h2>
<p>Bayes factor and posterior probability of each hypothesis are reported in Table~<a href="BF-int.html#tab:table-bf-results-int">10.1</a>.</p>
<table class="table table-hover" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:table-bf-results-int">Table 10.1: </span>Bayes factor encompassing model and hypothesis posterior probabilities (<span class="math inline">\(n_{subj} = 847\)</span>).
</caption>
<thead>
<tr>
<th style="text-align:right;font-weight: bold;">
Hypothesis
</th>
<th style="text-align:center;font-weight: bold;">
Bayes Factor
</th>
<th style="text-align:center;font-weight: bold;">
Posterior Probability
</th>
<th style="text-align:center;font-weight: bold;">
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
Null
</td>
<td style="text-align:center;">
3.5e+11
</td>
<td style="text-align:center;">
0.03
</td>
<td style="text-align:center;width: 50pt; vertical-align:middle;padding-bottom: 0px;">
<img src="images/ball_BF_int_null.png" width="40" height="40">
</td>
</tr>
<tr>
<td style="text-align:right;">
Monotropy
</td>
<td style="text-align:center;">
9.2e+12
</td>
<td style="text-align:center;">
0.92
</td>
<td style="text-align:center;width: 50pt; vertical-align:middle;padding-bottom: 0px;">
<img src="images/ball_BF_int_monotropy.png" width="40" height="40">
</td>
</tr>
<tr>
<td style="text-align:right;">
Hierarchy
</td>
<td style="text-align:center;">
4.7e+11
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;width: 50pt; vertical-align:middle;padding-bottom: 0px;">
<img src="images/ball_BF_int_hierarchy.png" width="40" height="40">
</td>
</tr>
<tr>
<td style="text-align:right;">
Independence
</td>
<td style="text-align:center;">
1.1e+10
</td>
<td style="text-align:center;">
0.00
</td>
<td style="text-align:center;width: 50pt; vertical-align:middle;padding-bottom: 0px;">
<img src="images/ball_BF_int_independence.png" width="40" height="40">
</td>
</tr>
<tr>
<td style="text-align:right;">
Integration
</td>
<td style="text-align:center;">
1.7e+10
</td>
<td style="text-align:center;">
0.00
</td>
<td style="text-align:center;width: 50pt; vertical-align:middle;padding-bottom: 0px;">
<img src="images/ball_BF_int_integration.png" width="40" height="40">
</td>
</tr>
</tbody>
</table>
<p>Prior sensitivity analysis is conducted considering the same prior as in the analysis of the externalizing problems. The results of the prior sensitivity analysis are reported in Table~<a href="BF-int.html#tab:table-sens-prior-analysis-int">10.2</a>.</p>
<table class="table table-striped table-hover" style="font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:table-sens-prior-analysis-int">Table 10.2: </span>Bayes factor encompassing model and hypothesis posterior probabilities (PP) under different prior settings (<span class="math inline">\(n_{subj} = 847\)</span>).
</caption>
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; font-weight: bold; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
<span class="math inline">\(\mathcal{N}(0, .5)\)</span>
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; font-weight: bold; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
<span class="math inline">\(\mathcal{N}(0, 1)\)</span>
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; font-weight: bold; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
<span class="math inline">\(\mathcal{N}(0, 3)\)</span>
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; font-weight: bold; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
<span class="math inline">\(\mathcal{N}(0, 5)\)</span>
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; font-weight: bold; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
<span class="math inline">\(\mathcal{N}(0, 10)\)</span>
</div>
</th>
</tr>
<tr>
<th style="text-align:right;font-weight: bold;">
Hypothesis
</th>
<th style="text-align:center;font-weight: bold;">
BF
</th>
<th style="text-align:center;font-weight: bold;">
PP
</th>
<th style="text-align:center;font-weight: bold;">
BF
</th>
<th style="text-align:right;font-weight: bold;">
PP
</th>
<th style="text-align:center;font-weight: bold;">
BF
</th>
<th style="text-align:center;font-weight: bold;">
PP
</th>
<th style="text-align:center;font-weight: bold;">
BF
</th>
<th style="text-align:right;font-weight: bold;">
PP
</th>
<th style="text-align:center;font-weight: bold;">
BF
</th>
<th style="text-align:center;font-weight: bold;">
PP
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;font-weight: bold;">
Null
</td>
<td style="text-align:center;">
3.8e+01
</td>
<td style="text-align:center;">
0.00
</td>
<td style="text-align:center;">
8.9e+04
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:center;">
3.5e+11
</td>
<td style="text-align:center;">
0.03
</td>
<td style="text-align:center;">
5.5e+14
</td>
<td style="text-align:right;">
0.09
</td>
<td style="text-align:center;">
1.8e+19
</td>
<td style="text-align:center;">
0.27
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;">
Monotropy
</td>
<td style="text-align:center;">
2.3e+04
</td>
<td style="text-align:center;">
0.29
</td>
<td style="text-align:center;">
1.8e+07
</td>
<td style="text-align:right;">
0.63
</td>
<td style="text-align:center;">
9.2e+12
</td>
<td style="text-align:center;">
0.92
</td>
<td style="text-align:center;">
5.4e+15
</td>
<td style="text-align:right;">
0.89
</td>
<td style="text-align:center;">
4.9e+19
</td>
<td style="text-align:center;">
0.72
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;">
Hierarchy
</td>
<td style="text-align:center;">
4.0e+04
</td>
<td style="text-align:center;">
0.51
</td>
<td style="text-align:center;">
8.8e+06
</td>
<td style="text-align:right;">
0.30
</td>
<td style="text-align:center;">
4.7e+11
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
1.0e+14
</td>
<td style="text-align:right;">
0.02
</td>
<td style="text-align:center;">
2.2e+17
</td>
<td style="text-align:center;">
0.00
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;">
Independence
</td>
<td style="text-align:center;">
5.7e+03
</td>
<td style="text-align:center;">
0.07
</td>
<td style="text-align:center;">
6.4e+05
</td>
<td style="text-align:right;">
0.02
</td>
<td style="text-align:center;">
1.1e+10
</td>
<td style="text-align:center;">
0.00
</td>
<td style="text-align:center;">
1.5e+12
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:center;">
1.6e+15
</td>
<td style="text-align:center;">
0.00
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;">
Integration
</td>
<td style="text-align:center;">
9.8e+03
</td>
<td style="text-align:center;">
0.13
</td>
<td style="text-align:center;">
1.4e+06
</td>
<td style="text-align:right;">
0.05
</td>
<td style="text-align:center;">
1.7e+10
</td>
<td style="text-align:center;">
0.00
</td>
<td style="text-align:center;">
1.5e+12
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:center;">
8.4e+14
</td>
<td style="text-align:center;">
0.00
</td>
</tr>
</tbody>
</table>
<p>Overall results consistently indicate the Monotropy Hypothesis as the most supported by the data. However, we can observe the same patterns as in the analysis of the externalizing problems. More diffuse prior, favour hypothesis with more equality constraints. Whereas, tighter prior penalizes hypotheses with more equality constraints.</p>
</div>
<div id="selected-model-3" class="section level2" number="10.5">
<h2><span class="header-section-number">10.5</span> Selected Model</h2>
<p>In the model, we consider only the role of gender and mother attachment as fixed effects of <span class="math inline">\(\mu\)</span>. In the R formula syntax, we have</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="BF-int.html#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># formula for p</span></span>
<span id="cb55-2"><a href="BF-int.html#cb55-2" aria-hidden="true" tabindex="-1"></a>p <span class="sc">~</span> gender <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>ID_class)</span>
<span id="cb55-3"><a href="BF-int.html#cb55-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-4"><a href="BF-int.html#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="co"># formula for mu</span></span>
<span id="cb55-5"><a href="BF-int.html#cb55-5" aria-hidden="true" tabindex="-1"></a>mu <span class="sc">~</span> gender <span class="sc">+</span> mother <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>ID_class)</span></code></pre></div>
<p>Again, we specify the same prior distributions as before. The resulting prior settings are</p>
<pre><code>##                   prior     class           coef    group resp dpar nlpar bound       source
##            normal(0, 3)         b                                                       user
##            normal(0, 3)         b        genderM                                (vectorized)
##            normal(0, 3)         b  motherAnxious                                (vectorized)
##            normal(0, 3)         b motherAvoidant                                (vectorized)
##            normal(0, 3)         b  motherFearful                                (vectorized)
##            normal(0, 3)         b                                zi             (vectorized)
##            normal(0, 3)         b        genderM                 zi             (vectorized)
##  student_t(3, 0.7, 2.5) Intercept                                                    default
##          logistic(0, 1) Intercept                                zi                  default
##    student_t(3, 0, 2.5)        sd                                                    default
##    student_t(3, 0, 2.5)        sd                                zi                  default
##    student_t(3, 0, 2.5)        sd                ID_class                       (vectorized)
##    student_t(3, 0, 2.5)        sd      Intercept ID_class                       (vectorized)
##    student_t(3, 0, 2.5)        sd                ID_class        zi             (vectorized)
##    student_t(3, 0, 2.5)        sd      Intercept ID_class        zi             (vectorized)
##       gamma(0.01, 0.01)     shape                                                    default</code></pre>
<p>The model is estimated using 6 independent chains with 6,000 iterations (warm-up 2,000). The model summary is presented below.</p>
<pre><code>##  Family: zero_inflated_negbinomial 
##   Links: mu = log; shape = identity; zi = logit 
## Formula: internalizing_sum ~ gender + mother + (1 | ID_class) 
##          zi ~ gender + (1 | ID_class)
##    Data: data (Number of observations: 847) 
## Samples: 6 chains, each with iter = 6000; warmup = 2000; thin = 1;
##          total post-warmup samples = 24000
## 
## Group-Level Effects: 
## ~ID_class (Number of levels: 50) 
##                  Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## sd(Intercept)        0.43      0.08     0.29     0.61 1.00     5203    10756
## sd(zi_Intercept)     2.18      0.53     1.35     3.43 1.00    11849    14075
## 
## Population-Level Effects: 
##                Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## Intercept          0.88      0.11     0.66     1.10 1.00     9744    13174
## zi_Intercept      -2.82      0.65    -4.33    -1.78 1.00    11781    12633
## genderM            0.07      0.07    -0.07     0.21 1.00    36050    19093
## motherAnxious      0.29      0.09     0.11     0.46 1.00    26032    19760
## motherAvoidant     0.12      0.10    -0.07     0.31 1.00    29724    20101
## motherFearful      0.48      0.12     0.25     0.71 1.00    26736    20112
## zi_genderM        -0.29      0.39    -1.06     0.46 1.00    28148    18297
## 
## Family Specific Parameters: 
##       Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## shape     2.53      0.33     1.95     3.25 1.00    21936    18166
## 
## Samples were drawn using sampling(NUTS). For each parameter, Bulk_ESS
## and Tail_ESS are effective sample size measures, and Rhat is the potential
## scale reduction factor on split chains (at convergence, Rhat = 1).</code></pre>
Marginal effects are presented in Figure~<a href="BF-int.html#fig:plot-marginal-int">10.1</a> and differences between mother attachment patterns are reported in Figure~<a href="BF-int.html#fig:plot-diff-int">10.2</a>.
<div class="figure" style="text-align: center"><span id="fig:plot-marginal-int"></span>
<img src="attachment-bayes-factor_files/figure-html/plot-marginal-int-1.png" alt="Marginal predicted values according to gender and mother attachment ($n_{subj} = 847$)." width="95%" />
<p class="caption">
Figure 10.1: Marginal predicted values according to gender and mother attachment (<span class="math inline">\(n_{subj} = 847\)</span>).
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:plot-diff-int"></span>
<img src="attachment-bayes-factor_files/figure-html/plot-diff-int-1.png" alt="Predicted differences between mother attachment patterns ($n_{subj} = 847$)." width="672" />
<p class="caption">
Figure 10.2: Predicted differences between mother attachment patterns (<span class="math inline">\(n_{subj} = 847\)</span>).
</p>
</div>
<p>Overall, results indicate that Fearful, and Anxious children have more problems than Secure children. Moreover, Fearful children have more problems than Avoidant children. Finally, also the difference between Avoidant and Anxious children is close to the threshold.</p>
<p>To evaluate the fit of the model to the data, we computed the <em>Bayesian</em> <span class="math inline">\(R^2\)</span> using the function <code>brms::bayes_R2()</code>, and we present Posterior Predictions in Figure~<a href="BF-int.html#fig:plot-ppcheck-int">10.3</a>.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="BF-int.html#cb58-1" aria-hidden="true" tabindex="-1"></a>r2_int</span>
<span id="cb58-2"><a href="BF-int.html#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="do">##     Estimate  Est.Error      Q2.5    Q97.5</span></span>
<span id="cb58-3"><a href="BF-int.html#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="do">## R2 0.2224337 0.02977471 0.1651088 0.281678</span></span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:plot-ppcheck-int"></span>
<img src="attachment-bayes-factor_files/figure-html/plot-ppcheck-int-1.png" alt="Posterior predictive check ($n_{subj} = 847$)." width="672" />
<p class="caption">
Figure 10.3: Posterior predictive check (<span class="math inline">\(n_{subj} = 847\)</span>).
</p>
</div>
<p>We can see that the actual variance explained by fixed effects and random effects is around 22%. Moreover, the posterior predictive check indicates a good fit to the data.</p>
<div id="conclusions-5" class="section level4 unnumbered">
<h4>Conclusions</h4>
<p>Considering attachment theoretical perspectives, results indicate only the role of mother attachment so we can support the Monotropy Theory.</p>

</div>
</div>
</div>
<hr>
<center>
  <div class="footer">
    All materials <a href= "https://creativecommons.org/licenses/by/2.0/"> CC-BY </a> unless noted otherwise.
    <br>
    To know more about <span style="color: #8C3031; font-weight:bold"> Psicostat</span> and our activities visit <a href= "https://psicostat.dpss.psy.unipd.it/">https://psicostat.dpss.psy.unipd.it/</a>.
  </div>
</center>
            </section>

          </div>
        </div>
      </div>
<a href="model-comparison-int.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="conclusion-int.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": true
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/ClaudioZandonella/Attachment/edit/master/10-int-BF.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["attachment-bayes-factor.pdf"],
"toc": {
"collapse": "section",
"scroll_highlight": true,
"toc_float": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
